[env]
TERM = "xterm-256color"

[general]
import = [
#    "~/.config/alacritty/themes/themes/solarized_dark.toml"
    "~/.config/alacritty/themes/themes/dark_plus.toml"
    #"~/.config/alacritty/themes/themes/carbonfox.toml"
]

[terminal.shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "block"

[font]
size = 13.0

[font.normal]
family = "CodeNewRoman Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.96

[window.padding]
x = 10
y = 10

[window.dimensions]
columns = 140
lines = 46
